### ISSUE TITLE
Go to definition does not work with Jinja Template files

### ISSUE THREAD

**Issue by rbhanot4739** [wholroyd/vscode-jinja#28]
**VSCode Version** :1.33.1
**OS Version**: Ubuntu 16.04 LTS

I am working on a Python Flask project which has number of Jinja Template files. The native Go to Definition/Declaration functionality does not work with Jinja files. I am not sure if it is a problem with Python extension not supporting Jinja files or VsCode not supporting Jinja files yet.

Steps to Reproduce:

I have the following snippet from my Jinja template file.

```
{% extends "base.html" %}
{% from "_posts_jinja.html" import delete_post %}
{% block body %}
```
Now If I try to jump to let's say `base.html` or `_posts_jinja.html` file or to `delete_post` macro which has been defined inside the `_posts_jinja.html`, VsCode shows a popup balloon saying "no definition can be found" for this symbol.

Infact these symbols in Jinja/html files are not even recognized or indexed because if I hit ctrl-t and try to look up for `delete_post` macro, it does not show up. However the other symbols in the python files show up just fine.

I am not sure if this is the issue with Jinja extension or Python extension, but since Goto definitions work just fine with regular python files, I suspect this to be related to Jinja files.

**Comment by wholroyd** [comment]
This plugin doesn't provide any language construction logic (like ability to understand code between different files in a project), it's only a syntax highlighter. I would say it's possibly an issue with the Python plugin since it should be providing that functionality.

However, VSCode has been known to have issues with two plugins that identify with a particular file type. I've stopped development on this plugin because of issues relating to it.
