### ISSUE TITLE
Extension doesn't work as of VSCode 1.5.2

### ISSUE THREAD

**Issue by amamut** [wholroyd/vscode-jinja#7]
Installed and enabled extension with vscode v1.5.2 and confirmed by seeing that html file is marked as "Jinja". Syntax coloring doesn't work but I'm not sure if one my other extensions is breaking it. Is there a way to check?

Thanks.

**Comment by wholroyd** [comment]
I'm using Code v1.8 and have been using it since v0.10, the extension has always worked between those two versions. Syntax coloring is literally just a JSON file with regular expression statements - Code does all the magic itself. It's possible that you may need to set it to HTML and see if it bounces back to Jinja with coloring?

You could try disabling the plugins that deal with HTML and see which one makes it start working again.

**Comment by wholroyd** [comment]
Have a fix coming soon.

**Comment by wholroyd** [comment]
Fixed with #15
